#!/bin/sh

# Load RGB libs
. "$(dirname -- "$0")/packages/rgb/src/rgb"

readonly run_path=./packages/$1/src
if [ ! -d "$run_path" ]; then
    rgb "Package '$1' not found" $RED
    exit 1
fi

chmod +x "$run_path/$1"

./packages/$1/src/$1