#!/bin/sh

# Load RGB libs
. "$(dirname -- "$0")/utils"

RUN_PACKAGE=$1

export PACKAGES_DIR="packages"
export BIN_PATH="bin"
export SPEC_DIR="spec"
export ROOT_PATH="$PWD"

readonly run_path=./$PACKAGES_DIR/$1
if [ ! -d "$run_path" ]; then
    echo -e "$error Package '$1' not found"
    exit 1
fi

chmod +x "$run_path/$1"

shift 1

RUN_FILE="$PACKAGES_DIR/$RUN_PACKAGE/$BIN_PATH/$RUN_PACKAGE"

chmod +x $RUN_FILE

./$RUN_FILE $@