#!/bin/sh

. ./packages/rgb/rgb
. ./utils

PACKAGE=$1
export PACKAGES_DIR="packages"
export SPEC_DIR="spec"
export ROOT_PATH="$PWD"
export FAILED_FILE="TEMPORARY_FAILED_TESTS"
export PASSED_FILE="TEMPORARY_PASSED_TESTS"
export SKIPPED_FILE="TEMPORARY_SKIPPED_TESTS"

result() {
    cd "$ROOT_PATH"

    FAILS=$(cat $FAILED_FILE)
    PASS=$(cat $PASSED_FILE)
    SKIPS=$(cat $SKIPPED_FILE)

    rm -rf $FAILED_FILE $PASSED_FILE $SKIPPED_FILE

    sumMatches() {
        total=0
        
        for num in $@; do
            total=$((total + num))
        done

        echo $total
    }

    FAILS_MATCH=$(sumMatches $FAILS)
    PASS_MATCH=$(sumMatches $PASS)
    SKIPS_MATCH=$(sumMatches $SKIPS)

    echo

    printf "$(rgb -b "SKIPS: $(rgb "$SKIPS_MATCH" $YELLOW)" $YELLOW)"
    printf "$(rgb -b "\tPASS: $(rgb "$PASS_MATCH" $GREEN)" $GREEN)"
    printf "$(rgb -b "\t\tFAILS: $(rgb "$FAILS_MATCH" $RED)" $RED)\n"
}

run_test() {
    local PACKAGE=${1}

    PACKAGE_PATH="$PACKAGES_DIR/$PACKAGE"

    echo

    if [ ! -d "$PACKAGE_PATH" ]; then
        echo -e "$error Package '$PACKAGE' not found at '$PWD/$PACKAGE_PATH'"
        exit 1
    fi

    cd "$PACKAGE_PATH"

    if [ ! -d "$SPEC_DIR" ]; then
        echo -e "$error $SPEC_DIR folder not found at '$PWD/$SPEC_DIR'"
        mkdir $PWD/$SPEC_DIR
        exit 1
    fi

    cd "$SPEC_DIR"

    TEST_FILES=$(ls)

    if [ -z "$TEST_FILES" ]; then
        echo -e "$error no tests files were found at '$PWD'"
        exit 1
    fi

    echo "$title $(rgb "testing '$PACKAGE' package..." $BLUE)"

    for TEST in $TEST_FILES; do
        echo "$title $(rgb "running '$TEST' file" $BLUE)"
        chmod +x $TEST
        ./$TEST
    done

    cd $ROOT_PATH
}

if [ ! -z "$PACKAGE" ]; then
    run_test $PACKAGE
    result

    exit 0
fi

PACKAGES=$(ls $PACKAGES_DIR)

for PACKAGE in $PACKAGES; do
    run_test $PACKAGE
done

result

exit 0
