#!/bin/sh

if ! [ -z $ALREADY_EXPORTED ]; then
    echo "error: the packages already been exported"
    echo "restart the environment process first"
fi

addPath() {
    local filePath=${1}

    if ! [ -d "$filePath" ]; then
        echo "error: the provided file '$filePath' does not exist"
    fi

    echo "Exporting: '$filePath'"
    export PATH="$filePath:$PATH"
}

if ! [ -d "$PWD/bin" ]; then
    echo "error: the bin directory does not exist"
    echo "please run the Makefile first"
fi

bin_targets=$(sh -c "ls $PWD/bin")

addPath $PWD/scripts

for bin in $bin_targets; do
    addPath $PWD/bin/$bin
done
