#!/bin/sh

source ./scripts/utils

if [[ $? -gt 0 ]]; then
    echo "error: you need to be in the repository path" >&2
    return
fi

only_execute_with_source

if [[ $? -gt 0 ]]; then
    exit 1
fi

if ! [[ -z $BINARA_EXPORTED_PATHS ]]; then
    error "paths are already exported"
    return 1;
fi

dirs=(
    scripts
)

for dir in $dirs; do
    info "add to path: $dir"
    export PATH="$dir:$PATH"
done

BINARA_EXPORTED_PATHS=true
