#!/bin/sh

set -e

BINARA_HOME="$HOME/.binara"
BIN_DIR="bin"
PACKAGES_DIR="packages"
SOURCE_MAP_FILE="sourceMap.txt"

createDir() {
    local location=${1}
    echo "Creating dir: $location"
    mkdir -p $location
}

cloneFile() {
    local from=${1}
    local to=${2}

    echo "Cloning file: '$from'"
    cp -r $from $to
}

home() {
    local path=${1}
    echo $BINARA_HOME/$path
}

bin() {
    local path=${1}
    echo $(home $BIN_DIR/$path)
}

package() {
    local path=${1}
    echo $(home $PACKAGES_DIR/$path)
}

makeLinkBin() {
    local bin=${1}
    local linkTarget="$(bin $(basename $bin))"

    echo "Linking: $1 to $linkTarget"
    ln -sf "$bin" "$linkTarget"
}


echo "removing: '$HOME/.binara'"
rm -rf $BINARA_HOME

createDir $(home)
createDir $(bin)
createDir $(package)

cloneFile sourceMap.txt $(home)
cloneFile packages $(home)

makeLinkBin $(package binara/binara)
makeLinkBin $(package core/core)

SHELL_NAME=$(basename $SHELL)

showExportMessage() {
    echo "manually paste the $BINARA_HOME variable into your shell configuration file:"
    echo
    echo 'export $BINARA_HOME=$HOME/.binara'
    exit 1
}

if [ ! -z $SHELL_NAME ]; then
    SHELL_RC=".$SHELL_NAME""rc"
    RC_PATH="$HOME/$SHELL_RC"

    echo "Shell '$SHELL_NAME' detected, trying to insert \$BINARA_HOME environment on '$HOME/$SHELL_RC'"

    if [ ! -f "$RC_PATH" ]; then
        echo "error: cannot find the file '$RC_PATH'"
        showExportMessage
    fi
    
    RC_CONTENT=$(cat "$RC_PATH")
    EXPORT_BINARA_HOME='export BINARA_HOME=$HOME/.binara'
    EXPORT_BINARA_BIN_PATH='export PATH="$BINARA_HOME/bin:$PATH"'
    CORE_PATH='export CORE="$BINARA_HOME/bin/core"'

    if ! [[ "$RC_CONTENT" =~ "$EXPORT_BINARA_HOME" ]]; then
        echo $EXPORT_BINARA_HOME >> $RC_PATH
    fi

    if ! [[ "$RC_CONTENT" =~ "$EXPORT_BINARA_BIN_PATH" ]]; then
        echo $EXPORT_BINARA_BIN_PATH >> $RC_PATH
    fi

    if ! [[ "$RC_CONTENT" =~ "$CORE_PATH" ]]; then
        echo $CORE_PATH >> $RC_PATH
    fi
else
    echo "error: shell name not found."
    showExportMessage
fi
